export const ScreenNames = {
  SplashScreen: 'SplashScreen',
  LoginScreen: 'LoginScreen',
  RegisterScreen: 'RegisterScreen',
  ExplorerScreen: 'ExplorerScreen',
  MateScreen: 'MateScreen',
  LocationScreen: 'LocationScreen',
  MessageScreen: 'MessageScreen',
  ProfileScreen: 'ProfileScreen',
  TabsScreen: 'TabsScreen',
  MateScreenDetail: 'MateScreenDetail',
  Update: 'Update',
  ListProductScreen: 'ListProductScreen',
  ChatRoomScreen: 'ChatRoomScreen',
  LiveStream: 'Livestream',
  InformationRoom: 'InformationRoom',
  VideoCallScreen: 'VideoCallScreen',
  VideoCall: 'VideoCall',
  List: 'List',
  WebScreen:'WebScreen',
  NewPostScreen: 'NewPostScreen',
  PostDetailScreen: 'PostDetailScreen',
  SocialScreen : 'SocialScreen',
  PropertyScreen : 'PropertyScreen',
  ChatRoomGroupScreen: 'ChatRoomGroupScreen',
  GroupMateScreen: 'GroupMateScreen',
  PropertyListScreen: 'PropertyListScreen',
  PropertyDetailScreen: 'PropertyDetailScreen',
  Account: 'Account',
  Scanner: 'Scanner',
  CoffeeScreen: 'CoffeeScreen',
  CoffeeDetailScreen: 'CoffeeDetailScreen',
  RestaurantScreen: 'RestaurantScreen',
  RestaurantDetailScreen: 'RestaurantDetailScreen'
};

export default {
  ScreenNames,
};
